### ISSUE TITLE
请问为什么我用html2json解析出来的nodes赋值给data之后的样式全部加了“，”...

### ISSUE THREAD

**Issue by ExcellentJR** [suinia/mpvue-htmlParse#1]
![wechatimg12](https://user-images.githubusercontent.com/14272879/42090535-698fa0e0-7bd4-11e8-8ceb-5968105b4f4e.jpeg)
![wechatimg13](https://user-images.githubusercontent.com/14272879/42090543-703ec696-7bd4-11e8-8ae0-84af4a090470.jpeg)
如上面两张图，第一张是展示出来的效果里面的style，第二张图是html2json解析出来的nodes数组里面的style，请问我有na li哪里用的不对吗？

**Comment by suinia** [comment]
当时我做的时候记得 html2json 转style有点问题，我自己改了下。
回头我在这个库里面提供下html2json的功能。

**Comment by ExcellentJR** [comment]
@suinia 老哥今天有时间搞一下吗？

**Comment by suinia** [comment]
我更新了下代码，你是用npm依赖包吗？那我需要更新下包

**Comment by ExcellentJR** [comment]
@suinia 依赖包还没更新是吧？还是我自己可以直接下载lib下面的去用？

**Comment by ExcellentJR** [comment]
@suinia 老哥儿有时间更新下吧，我本来想直接下载去用，但是想到我这项目里有esLint就放弃了...不然还得改很多地方

**Comment by suinia** [comment]
@ExcellentJR 更新了。
`<htmlParse :html="html"  />`

**Comment by ExcellentJR** [comment]
@suinia 很感谢！但是我现在遇到了另外的问题就是，渲染是渲染出来了，速度也挺快，但是所有图片的宽高的单位全是px的，导致图片显示不正常，把px换成rpx就正常了，这个问题你有遇到过吗？我把渲染前的字符串里的px全部替换成了rpx也没用，图片还是按照px的单位来渲染的

**Comment by suinia** [comment]
因为对图片高宽做了计算处理。可以提供一段有图片的html？我试试看。

**Comment by ExcellentJR** [comment]
@suinia htmlText='<section class="" powered-by="xiumi.us" style="margin: 0px; padding: 0px; max-width: 100%; letter-spacing: 0.544px; text-align: justify; word-wrap: break-word !important;"><section class="" style="margin: 0px; padding: 0px; max-width: 100%; text-align: center; word-wrap: break-word !important;"><section class="" style="margin: 0px; padding: 0px; max-width: 100%; vertical-align: middle; display: inline-block; word-wrap: break-word !important; overflow: hidden !important;"><img data-ratio="0.4546875" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/3XicGGH06p2cksThAHWBvhM7nmefhLeia5PSAIVu8QeY6JZ0M1tHjN68CYWzocS0RNNVfTRcru2U0IrETmmlOZwg/640?wx_fmt=jpeg" data-type="jpeg" data-w="640" class="" src="https://mmbiz.qpic.cn/mmbiz_jpg/3XicGGH06p2cksThAHWBvhM7nmefhLeia5PSAIVu8QeY6JZ0M1tHjN68CYWzocS0RNNVfTRcru2U0IrETmmlOZwg/640?wx_fmt=jpeg&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1" data-fail="0" style="margin: 0px; padding: 0px; max-width: 100%; height: auto !important; word-wrap: break-word !important; width: auto !important; visibility: visible !important;"></section></section></section>'

**Comment by ExcellentJR** [comment]
@suinia 以下就是一段展示的变宽的图片htmlText`<section class="" powered-by="xiumi.us" style="margin: 0px; padding: 0px; max-width: 100%; letter-spacing: 0.544px; text-align: justify; word-wrap: break-word !important;"><section class="" style="margin: 0px; padding: 0px; max-width: 100%; text-align: center; word-wrap: break-word !important;"><section class="" style="margin: 0px; padding: 0px; max-width: 100%; vertical-align: middle; display: inline-block; word-wrap: break-word !important; overflow: hidden !important;"><img data-ratio="0.4546875" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/3XicGGH06p2cksThAHWBvhM7nmefhLeia5PSAIVu8QeY6JZ0M1tHjN68CYWzocS0RNNVfTRcru2U0IrETmmlOZwg/640?wx_fmt=jpeg" data-type="jpeg" data-w="640" class="" src="https://mmbiz.qpic.cn/mmbiz_jpg/3XicGGH06p2cksThAHWBvhM7nmefhLeia5PSAIVu8QeY6JZ0M1tHjN68CYWzocS0RNNVfTRcru2U0IrETmmlOZwg/640?wx_fmt=jpeg&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1" data-fail="0" style="margin: 0px; padding: 0px; max-width: 100%; height: auto !important; word-wrap: break-word !important; width: auto !important; visibility: visible !important;"></section></section></section>`

**Comment by suinia** [comment]
@ExcellentJR 加了dp计算 更新下依赖 `1.0.2`

**Comment by ExcellentJR** [comment]
@suinia 你好，图片显示正常了，但是在图片过多的情况下还是会有较长时间的白屏时间（我这的需求里面有挺多图片的，大概十几二十张，可能还会有动图，微信的公众号文章是有图片懒加载的效果的，但是产品不想直接放公众号的网页链接进来。。。），你有考虑过加上图片懒加载的效果吗？占位图或者其他的方式？

**Comment by suinia** [comment]
小程序支持 lazy-load 。回头我试试效果

**Comment by ExcellentJR** [comment]
@suinia 想加个loading效果，一进入页面开始loading，然后需要确定什么时候会有东西渲染到页面上，这个时候loading停止（不是获取到htmlText的时候停止），请问目前可以实现吗？

**Comment by ExcellentJR** [comment]
图片预加载的自己在你这个项目的基础上修改了下基本可以满足需求了。。。
